# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage
language: swift
osx_image: xcode12

env:
  global:
    - SCAN_WORKSPACE=Example/RxUI.xcworkspace
    
before_install:
  - brew outdated carthage || brew upgrade carthage
# before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  #- carthage bootstrap
script:
  - fastlane ci_commit

deploy:
  skip_cleanup: true
  provider: script
  script: fastlane framework_release
  on:
    tags: true
